# -*- coding: utf-8 -*-
"""gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwUNrNNuYoHmrcB0__uOjyClT5MKBQ8E
"""





!pip install -U google-generativeai

from google import genai
client = genai.Client(api_key="")

import pandas as pd
df_pairs = pd.read_csv('/content/berttext_clustering (1).csv')

import pandas as pd
import random
import math
import re
import json
import time
from itertools import product
import google.generativeai as genai

# ------------------------------------------
# Initialize Gemini client
# ------------------------------------------
genai.configure(api_key="")
model = genai.GenerativeModel("gemini-2.5-flash-lite")

new_reqs = []

# ------------------------------------------
# Iterate over clusters
# ------------------------------------------
for cluster, group in df_pairs.groupby("cluster_name"):

    # 🟡 Skip problematic cluster
    if cluster.strip().lower() == "miscellaneous":
        print(f"⏭️ Skipping problematic cluster '{cluster}'")
        continue

    cluster_texts = "\n".join(group["description"].dropna().tolist())

    prompt = f"""
    You are analyzing a group of software requirement statements related to the cluster: '{cluster}'.

    From the following text, extract **distinct meaningful phrases** that represent:
    - "system" → the main software name, system name, feature name or platform name (e.g., Zoom, Webex, app, meeting platform). If not present, use "software system" or "webex" as a fallback.
    - "process" → an action or operation users can perform (e.g., schedule, join, share, enable)
    - "object" → the thing being acted upon (e.g., meeting, video, chat, participants)
    - "details" → extra context or purpose (e.g., with single sign-on, across devices, with reactions)

    Text:
    ---
    {cluster_texts}
    ---

    You must output ONLY valid JSON with this exact format:
    {{
      "system": ["..."],
      "process": ["..."],
      "object": ["..."],
      "details": ["..."]
    }}
    Only use terms that exactly appear in the text above.
    """

    # ------------------------------------------
    # Gemini call (with retry and delay)
    # ------------------------------------------
    for attempt in range(2):  # retry once if it fails
        try:
            response = model.generate_content(prompt)
            time.sleep(2)  # prevent rate-limit issues
            content = response.text.strip()

            match = re.search(r"\{.*\}", content, re.DOTALL)
            if not match:
                raise ValueError("No valid JSON found in response")

            data = json.loads(match.group(0))
            break  # success, exit retry loop

        except Exception as e:
            if attempt == 0:
                print(f" Retry for cluster '{cluster}' due to error: {e}")
                time.sleep(3)
                continue
            else:
                print(f" Fallback for cluster '{cluster}' after repeated failure.")
                data = {
                    "system": ["software system"],
                    "process": ["provide"],
                    "object": ["feature"],
                    "details": ["for user convenience"]
                }

    # ------------------------------------------
    # Process JSON into boilerplate requirements
    # ------------------------------------------
    systems = data.get("system", [])
    processes = data.get("process", [])
    objects = data.get("object", [])
    details = data.get("details", [])

    if not systems or not processes or not objects:
        print(f"Missing attributes in cluster '{cluster}', using fallback terms.")
        systems = systems or ["software system"]
        processes = processes or ["provide"]
        objects = objects or ["feature"]
        details = details or ["for user convenience"]

    text_lines = group["description"].dropna().tolist()
    unique_terms = [re.findall(r"\b[a-zA-Z][a-zA-Z0-9_\-\s]+\b", t.lower()) for t in text_lines]

    def came_from_same_req(a, b):
        for terms in unique_terms:
            if a.lower() in " ".join(terms) and b.lower() in " ".join(terms):
                return True
        return False

    all_combos = list(product(systems, processes, objects, details))
    filtered_combos = [
        (s, p, o, d)
        for s, p, o, d in all_combos
        if not (came_from_same_req(s, p) or came_from_same_req(p, o) or came_from_same_req(o, d))
    ]

    total_combinations = len(all_combos)
    filtered_total = len(filtered_combos)

    if not filtered_combos:
        s = systems[0]
        p = processes[0]
        o = objects[0]
        d = details[0]
        filtered_combos = [(s, p, o, d)]

    # Limit number of generated requirements
    if filtered_total <= 10:
        sample_size = filtered_total
    elif filtered_total <= 50:
        sample_size = math.ceil(filtered_total * 0.5)
    else:
        sample_size = min(filtered_total, 20 + len(processes))

    sampled_combos = random.sample(filtered_combos, min(sample_size, filtered_total))

    for s, p, o, d in sampled_combos:
        new_req = f"{s} shall provide users with the ability to {p} {o} {d}".strip()
        new_reqs.append({
            "feature_title": "",
            "description": "",
            "cluster_name": cluster,
            "system": s,
            "process": p,
            "object": o,
            "details": d,
            "boilerplate_requirement": new_req
        })

    print(f"{cluster}: Generated {len(sampled_combos)}/{filtered_total} diverse boilerplate requirements.")

# ------------------------------------------
# Save results
# ------------------------------------------
df_boilerplate = pd.DataFrame(new_reqs)
df_boilerplate.to_csv("boilerplate_generated_requirements_gemini.csv", index=False)
print("Gemini-based boilerplate requirements saved to boilerplate_generated_requirements_gemini.csv")

import pandas as pd
df_boilerplate = pd.read_csv('/content/boilerplate_generated_requirements_gemini.csv')
df_copy= df_boilerplate.copy()

import pandas as pd
import time
import google.generativeai as genai

# Initialize Gemini client
genai.configure(api_key="")
model = genai.GenerativeModel("gemini-2.5-flash-lite")


# --------------------------------------------------
# 2️⃣ Define conversion function
# --------------------------------------------------
def convert_to_ieee(text):
    """
    Convert a functional or boilerplate requirement into IEEE 1012-2024 style phrasing.
    """
    if not isinstance(text, str) or not text.strip():
        return text

    prompt = f"""
You are an expert in IEEE 1012-2024 software requirements specification.
Rephrase the following requirement into IEEE-compliant phrasing with correct grammar,
precise technical tone, and modal verbs such as "shall", "must", or "should" as appropriate.
Output ONLY the rephrased version — no commentary or explanations.

Requirement:
{text}
"""

    try:
        response = model.generate_content(prompt)
        # time.sleep(2)  # Pause between requests to avoid rate limits

        # Safely extract Gemini output
        if hasattr(response, "text") and response.text:
            return response.text.strip()
        elif hasattr(response, "candidates") and len(response.candidates) > 0:
            return response.candidates[0].content.parts[0].text.strip()
        else:
            print(" Empty response for:", text[:60])
            return text

    except Exception as e:
        print(f" Error for requirement: {text[:60]}... — {e}")
        time.sleep(5)
        return text

# --------------------------------------------------
# 3️⃣ Load your CSV
# --------------------------------------------------
input_file = "/content/boilerplate_generated_requirements_gemini.csv"  # Replace with your file name
df = pd.read_csv(input_file)

# --------------------------------------------------
# 4️⃣ Apply Gemini model to each requirement
# --------------------------------------------------
print("Converting requirements to IEEE standard phrasing...\n")

ieee_results = []
for i, req in enumerate(df["boilerplate_requirement"], start=1):
    ieee_req = convert_to_ieee(req)
    ieee_results.append(ieee_req)
    print(f"✅ Processed {i}/{len(df)}: {req[:50]}...")

# --------------------------------------------------
# 5️⃣ Save final results
# --------------------------------------------------
df["ieee_requirement"] = ieee_results
output_file = "IEEE_Standard_Requirements.csv"
df[["boilerplate_requirement", "ieee_requirement"]].to_csv(output_file, index=False)

print(f"\n Done! Saved IEEE-style requirements to: {output_file}")

output_file = "IEEE_Standard_Requirements.csv"
df[["cluster_name","boilerplate_requirement", "ieee_requirement"]].to_csv(output_file, index=False)

print(f"\n Done! Saved IEEE-style requirements to: {output_file}")

"""## creative one selection for hhuman evaluation"""



import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util

# --- Load both CSVs ---
df_gpt = pd.read_csv("/content/selected_requirements_per_cluster.csv")
df_gemini = pd.read_csv("/content/gemini_IEEE_Standard_Requirements (1).csv")



# --- Rename columns to standardize ---
df_gpt = df_gpt.rename(columns={"selected_requirement": "gpt_req", "cluster_name": "cluster"})
df_gemini = df_gemini.rename(columns={"ieee_requirement": "gemini_req", "cluster_name": "cluster"})

# --- Load a strong sentence embedding model ---
model = SentenceTransformer('all-mpnet-base-v2')

selected_pairs = []

# --- Compare each GPT requirement to all Gemini requirements in the same cluster ---
for cluster, gpt_row in df_gpt.groupby("cluster"):
    gpt_text = gpt_row["gpt_req"].iloc[0]
    gemini_group = df_gemini[df_gemini["cluster"] == cluster]

    if gemini_group.empty:
        continue  # skip if no Gemini data for this cluster

    # Compute embeddings
    emb_gpt = model.encode(gpt_text, convert_to_tensor=True)
    emb_gemini = model.encode(gemini_group["gemini_req"].tolist(), convert_to_tensor=True)

    # Compute cosine similarity
    similarities = util.cos_sim(emb_gpt, emb_gemini)[0].cpu().numpy()

    # Pick the Gemini requirement with the highest similarity
    best_idx = np.argmax(similarities)
    best_req = gemini_group.iloc[best_idx]["gemini_req"]
    best_score = similarities[best_idx]

    selected_pairs.append({
        "cluster": cluster,
        "gpt_requirement": gpt_text,
        "best_gemini_requirement": best_req,
        "similarity_score": round(float(best_score), 4)
    })

# --- Save results ---
df_selected = pd.DataFrame(selected_pairs)
df_selected.to_csv("gemini_best_matched_to_gpt.csv", index=False)

print("✅ Saved most similar Gemini requirements per cluster to gemini_best_matched_to_gpt.csv")

import pandas as pd
df_gpt = pd.read_csv("selected_requirements_per_cluster.csv")
print(df_gpt.columns)
